/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package fi.vesas.autodiff;

import fi.vesas.autodiff.grad.Add;
import fi.vesas.autodiff.grad.Mul;
import fi.vesas.autodiff.grad.Value;
import fi.vesas.autodiff.nn.Tanh;

public class App {
    
    public void testMul() {

        Value x1 = new Value(2.0f);
        Value x2 = new Value(0.0f);

        Value w1 = new Value(-3.0f);
        Value w2 = new Value(1.0f);

        Value b = new Value(6.8813735870195432f);

        Mul x1w1 = new Mul(x1, w1);
        Mul x2w2 = new Mul(x2, w2);

        Add x1w1x2w2 = new Add(x1w1, x2w2);

        Tanh o = new Tanh(x1w1x2w2);

        System.out.println(x1w1.forward());

        /*
        InputLayer inputLayer = new InputLayer(2);
        inputLayer.setActivationFunction(new Relu());

        DenseLayer denseLayer = new DenseLayer(2, 2);
        denseLayer.setActivationFunction(new Relu());

        inputLayer.next(denseLayer);

        OutputLayer outputLayer = new OutputLayer(1);
        denseLayer.next(outputLayer);
        */
    }

    public static void main(String[] args) {
        new App().testMul();
    }
}
